name: getnews


on:
  schedule:
#    - cron:  '30 2 * * 1-5'
#    - cron:  '30 21 * * *'
  workflow_dispatch:
  
jobs:
  getstock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r getnewsreq.txt
      - name: Check Working Directory
        run: pwd
      - name: Run Python
        run:
          python scr/getnews/30GetVBNews.py;
      - name: Commit to github
        run:
          git config user.name  "${GITHUB_ACTOR}";
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com";
          git add .;
          git commit -m "WithGithubActions";
          git push;
          
