name: getstock


on:
#  schedule:
#    - cron:  '0 21 26 9 *'
  workflow_dispatch:
  
jobs:
  getstock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run:
          pwd
          python k/13PyGetInfo.py
      - name: git Setting
        run:
          git config --local user.email "fukuokamachivbc@gmail.com"
          git config --local user.name "fvbc"
      - name: Commit files
        run: 
          git add .
          git commit -m "WithGithubActions"
          git pull
          git push origin master
          
