name: getstock


on:
#  schedule:
#    - cron:  '0 21 26 9 *'
  workflow_dispatch:
  
jobs:
  getstock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check Working Directory
        run: pwd
      - name: Run Python
        run:
          python k/13PyGetInfo.py
      - name: git Setting
        run:
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Commit files
        run: 
          git add .
          git commit -m "WithGithubActions"
          git pull
          git push
          
